"""overhaul schema v2

Revision ID: 3a34acbc7db8
Revises: 48a368feef73
Create Date: 2026-05-14 22:14:57.721563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a34acbc7db8'
down_revision = '48a368feef73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_globais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('papeis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('permissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('regras_automacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('evento', sa.String(length=50), nullable=False),
    sa.Column('condicoes', sa.Text(), nullable=True),
    sa.Column('acoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papel_permissao',
    sa.Column('papel_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis.id'], ),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissoes.id'], ),
    sa.PrimaryKeyConstraint('papel_id', 'permissao_id')
    )
    op.create_table('usuario_papel',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('papel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'papel_id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cor', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dados_anteriores', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dados_novos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sla_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=True))

    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prazo_horas', sa.Integer(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tentativas_falhas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bloqueado_ate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('bloqueado_ate')
        batch_op.drop_column('tentativas_falhas')
        batch_op.drop_column('foto_perfil')

    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.drop_column('prazo_horas')

    with op.batch_alter_table('sla_logs', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('dados_novos')
        batch_op.drop_column('dados_anteriores')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_column('ativo')
        batch_op.drop_column('cor')
        batch_op.drop_column('icone')

    op.drop_table('usuario_papel')
    op.drop_table('papel_permissao')
    op.drop_table('regras_automacao')
    op.drop_table('permissoes')
    op.drop_table('papeis')
    op.drop_table('configuracoes_globais')
    # ### end Alembic commands ###
