"""add reset token fields to usuario

Revision ID: 48a368feef73
Revises: 08d1370371a3
Create Date: 2026-05-14 21:18:30.750091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a368feef73'
down_revision = '08d1370371a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_exp', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_usuarios_reset_token', ['reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_usuarios_reset_token', type_='unique')
        batch_op.drop_column('reset_token_exp')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
