"""Add subcategories, priority, internal messages and new statuses

Revision ID: 5a72fe6f85d1
Revises: 8d810892898c
Create Date: 2026-05-14 21:00:00.196620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a72fe6f85d1'
down_revision = '8d810892898c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('mensagens', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('is_interna', sa.Boolean(), nullable=True))

    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategoria_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_solicitacao_subcategoria', 'subcategorias', ['subcategoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_solicitacao_subcategoria', type_='foreignkey')
        batch_op.drop_column('subcategoria_id')

    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.drop_column('is_interna')

    op.drop_table('subcategorias')
    # ### end Alembic commands ###
