"""Add Artigo model v2

Revision ID: 8d810892898c
Revises: ffda3ab5b4dc
Create Date: 2026-05-14 19:53:23.884113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d810892898c'
down_revision = 'ffda3ab5b4dc'
branch_labels = None
depends_on = None


def upgrade():
	pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_categorias')
    # ### end Alembic commands ###


def downgrade():
	pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('_alembic_tmp_categorias',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    # sa.Column('descricao', sa.VARCHAR(length=200), nullable=True),
    # sa.Column('prazo_horas', sa.INTEGER(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('nome')
    # )
    # ### end Alembic commands ###
