"""Recreate DB with prazo_sla and updated structure

Revision ID: fc5a1434739a
Revises: 
Create Date: 2026-05-14 11:20:26.397223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5a1434739a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('atendente_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('prazo_sla', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atendente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitacoes_protocolo'), ['protocolo'], unique=True)

    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('de_status', sa.String(length=30), nullable=True),
    sa.Column('para_status', sa.String(length=30), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensagem_id', sa.Integer(), nullable=False),
    sa.Column('caminho', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mensagem_id'], ['mensagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anexos')
    op.drop_table('mensagens')
    op.drop_table('historico')
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitacoes_protocolo'))

    op.drop_table('solicitacoes')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('categorias')
    # ### end Alembic commands ###
