"""v2 schema updates

Revision ID: ffda3ab5b4dc
Revises: fc5a1434739a
Create Date: 2026-05-14 11:54:03.311207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffda3ab5b4dc'
down_revision = 'fc5a1434739a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('tabela', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('vencimento', sa.DateTime(), nullable=False),
    sa.Column('cumprido', sa.Boolean(), nullable=True),
    sa.Column('resolvido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_original', sa.String(length=150), nullable=True))

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prazo_horas', sa.Integer(), nullable=True))

    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conteudo', sa.Text(), nullable=False))
        batch_op.drop_column('mensagem')

    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prioridade', sa.String(length=20), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_column('prioridade')

    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensagem', sa.TEXT(), nullable=False))
        batch_op.drop_column('conteudo')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_column('prazo_horas')

    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.drop_column('nome_original')

    op.drop_table('sla_logs')
    op.drop_table('logs_auditoria')
    # ### end Alembic commands ###
